seed: 1515
workspace: 9000

# Training options
cost-type: ce-mean-words
max-length: 200
mini-batch: 1000
mini-batch-fit: true
maxi-batch: 10000
optimizer-params:
  - 0.9
  - 0.98
  - 1e-09
sync-sgd: true
optimizer-delay: 4
learn-rate: 0.0002
lr-decay-inv-sqrt:
  - 32000
lr-warmup: 32000
lr-report: true
clip-norm: 0
label-smoothing: 0.0
exponential-smoothing: 0.0001

# Validation set options
early-stopping: 30
beam-size: 1
normalize: 1
valid-mini-batch: 64
disp-first: 10
disp-freq: 1000u
valid-freq: 5000u
save-freq: 5000u
keep-best: true
