# Datasets are already TSV files
datasets:
  clean: /scratch/project_2005815/OpusTrainer/data/swh-eng/cleanmid.tsv # Concatenated clean and mid data
  medium: /scratch/project_2005815/OpusTrainer/data/swh-eng/dirty.tsv
  dirty: /scratch/project_2005815/OpusTrainer/data/swh-eng/backtranslated.tsv # With added <BT> tag

stages:
  - start
  - mid
  - end

start:
  - clean  0.8
  - medium 0.2
  - dirty  0
  - until clean 2 # Until two epochs of clean

mid:
  - clean  0.6
  - medium 0.3
  - dirty  0.1
  - until medium 1

end:
  - clean  0.4
  - medium 0.3
  - dirty  0.3
  - until dirty 5 # use `inf` to mean until forever

#modifiers:
#  - uppercase:
#    - probability: 0.05
#  - titlecase:
#    - probability: 0.05

seed: 1111
